### ISSUE TITLE
Fix problem with newly added blogs not showing in newsletter

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#225]

**Comment by goostleek** [comment]
It's (probably) caused by blogs directory structure change introduced in #217.

If you see the [`src/main/resources/application.yaml`](https://github.com/tdziurko/jvm-bloggers/pull/217/commits/67af1de559bab64f6d562aeb3e954cc0a693ab9f#diff-128181948a731701a44179a1edb9e167L15) configuration file, the location of blogs were updated to the new one but it's not deployed into production yet. The problem will be fixed after deploying the current version into production.

**Comment by tdziurko** [comment]
Hmm.. maybe. I am *almost-done* with docker-compose migration so release should be soon.

**Comment by tdziurko** [comment]
You're right. Closing.
