### ISSUE TITLE
Application can't fetch rss when it is available under https

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#67]
Example: 
https://touk.pl/blog/feed/ from @TouK

**Comment by daimonion** [comment]
If you need any help from our side (TouK) pls ping me.
Btw: http://touk.pl/blog/feed/ should work just fine?

**Comment by tdziurko** [comment]
When I try to open it via browser it redirects to https. But I need to check how it behaves in the application.

**Comment by daimonion** [comment]
You are right :) When I try to open http://touk.pl/blog/feed/ outside our network it redirects to https (I would never notice it because I'm on perma VPN even outside our firm). I'll try to contact our administrators maybe we could serve it via http (although https support in your app would be nice :) )

**Comment by alien11689** [comment]
It redirects to https on chrome, but from curl it works ok.

https://github.com/tdziurko/jvm-bloggers/pull/69
