### ISSUE TITLE
Fetching RSS at https://bialon.net/index.xml fails due to invalid xml.

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#84]
Exception

    p.t.j.blog_posts.RssCheckingActor        : Exception for rss from Marcin Białoń 
        (http://bialon.net//index.xml): com.sun.syndication.io.ParsingFeedException: 
        Invalid XML: Error on line 6: The element type "hr" must be terminated 
        by the matching end-tag "</hr>".

Still RSS online validator shows that rss of this blog is valid. So we should find a work around for this issue.

Note: Same issue occurs for rss at http://luksza.org/feed/atom/

**Comment by goostleek** [comment]
It's not the problem with validity of the _RSS_ feed. The problem is related to the `URLConnection` used in [`SyndFeedProducer`](https://github.com/tdziurko/jvm-bloggers/blob/28dbefd277e8b6eceec954b400c46fe9ffe5d39d/src/main/java/pl/tomaszdziurko/jvm_bloggers/utils/SyndFeedProducer.java#L25) which does not follow redirects. If you check the problematic URLs with _curl_ you can see that they both get `301` and HTML output instead expected _XML_:

 ```$  curl http://bialon.net//index.xml```

```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```
and the second one

````$ curl http://luksza.org/feed/atom/````

```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

The quick workaround for this is to just correct the problematic urls to its redirected location which, in this case, is HTTPS instead HTTP so it should be:
* https://bialon.net/index.xml (not ~~http://bialon.net/index.xml~~)
* https://luksza.org/feed/atom (not ~~http://luksza.org/feed/atom~~)

Nevertheless I will provide a fix for that to be able to follow redirects.

**Comment by tdziurko** [comment]
Ok, sound very good :)
